version: "3" #docker-compose version
services:
  web:
    build:
      context: . #assumes build is in current directory
      dockerfile: Dockerfile.dev #dockerfile for building the image
    ports:
      - "3000:3000" #mapping ports outside container to run within container
    volumes:
      - /app/node_modules
      #map that folder outside the container into the app folder inside the container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]